[versions]
neoforge = "26.1.0.0-alpha.5+snapshot-2"
mdg = "2.0.139"
neoforgeRange = { require = "[26.1.0.0-alpha.5+snapshot-2,)", prefer = "26.1.0.0-alpha.5+snapshot-2" }
neoform = "no"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
